### ISSUE TITLE
Timestamp does not work in sessions

### ISSUE THREAD

**Issue by didaquis** [riqui99/flypi#7]
The timestamp does not always work correctly. At the moment when it failed, the operating system was on time (checked by executing the command `date` in the terminal).

![foto](https://user-images.githubusercontent.com/6883041/42775823-ac4d0b66-8935-11e8-986a-08572588ed46.jpg)

I tried to reproduce this error on two different devices, but seems working fine.

I'm opening this issue to leave a record.

**Comment by riqui99** [comment]
How to reproduce it? Can you send me the session file?

**Comment by didaquis** [comment]
> How to reproduce it?


I'm working on it!

**Comment by didaquis** [comment]
[20180713_01.txt](https://github.com/riqui99/flypi/files/2207032/20180713_01.txt)

This is session file of screenshot

**Comment by riqui99** [comment]
🔍 ajaa, nice catch!!!!.... look at time, it's wrong formated, HH:MM:SS instead of millis... 

time is assigned in "self.time = json_data['time']", where json_data is comming from LoRa gateway, and probably with another format than the simulator that I did to develop the frontend.

Remember that I developed all software in a morning without the pi's. We need to solve this type of issues in live, we will check on the next meeting, and probably I take the globo+coche rpi and try to solve this type of issues with real hw/sw
